In [1]:
!pip install pyspark

Collecting pyspark
  Using cached pyspark-3.2.0.tar.gz (281.3 MB)
Collecting py4j==0.10.9.2
  Using cached py4j-0.10.9.2-py2.py3-none-any.whl (198 kB)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py): started
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): finished with status 'done'
  Created wheel for pyspark: filename=pyspark-3.2.0-py2.py3-none-any.whl size=281805913 sha256=ae42c4a65f80382e9de6fc202498dba4c3719b1505a64a6dc60c1d2ae71a3e49
  Stored in directory: c:\users\aniru\appdata\local\pip\cache\wheels\2f\f8\95\2ad14a4614b4a9f645ee928fbbd057b1b254c67adb494c9a58
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.2 pyspark-3.2.0

WARNING: You are using pip version 21.1.2; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\users\aniru\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

In [2]:
import numpy as np
import pandas as pd
import os
from datetime import datetime
from dateutil import parser
from pyspark.sql import SparkSession

In [3]:
os.chdir('..')

In [4]:
filename = 'Data\\csv\\Kerala.csv'

In [5]:
data_m = pd.read_csv(filename)
data_m

,Season,Sector,Category,Crop,QueryType,QueryText,KccAns,StateName,DistrictName,BlockName,CreatedOn
0,NaN,HORTICULTURE,Vegetables,Others,0,subsidy loan,contact nabard-0483 2734084,KERALA,ALAPPUZHA,KANJIKKUZHY,2013-04-02T17:08:34
1,NaN,HORTICULTURE,Condiments and Spices,Nutmeg,0,nut meg fertilizer application,apply potash-2 kg per tree per year,KERALA,ALAPPUZHA,AMBALAPPUZHA,2013-04-02T17:33:32
2,NaN,HORTICULTURE,Plantation Crops,Coconut,0,coconut button shedding,apply borax 250 gm per palm per year,KERALA,ALAPPUZHA,THYCATTUSSERY,2013-04-04T10:52:07
3,NaN,HORTICULTURE,Vegetables,Mushroom,0,mushroom cultivation-training,contact KVK -0479 2270495,KERALA,ALAPPUZHA,THYCATTUSSERY,2013-04-04T10:53:47
4,NaN,HORTICULTURE,Condiments and Spices,Nutmeg,0,nut meg drop,apply borax 250 gm per plant per year( in seve...,KERALA,ALAPPUZHA,ARYAD,2013-04-04T11:18:09
...,...,...,...,...,...,...,...,...,...,...,...
95395,NaN,AGRICULTURE,Others,Others,Government Schemes,Govt schemes for farmers.,--Recommended that various schemes are pm kisa...,KERALA,TRIVANDRUM,KAZHAKUTTAM,2021-09-24T18:08:54.71
95396,NaN,HORTICULTURE,Plantation Crops,Coconut,\tPlant Protection\t,Button shedding in coconut,Recommended to give 100g borax per palm per ye...,KERALA,TRIVANDRUM,KAZHAKUTTAM,2021-09-25T13:13:57.963
95397,NaN,HORTICULTURE,Fruits,Papaya,\tPlant Protection\t,Fungal disease in Papaya,Recommended to give copper oxy chloride 2g per...,KERALA,TRIVANDRUM,VARKALA,2021-09-27T10:03:47.577
95398,NaN,AGRICULTURE,Others,Others,Agriculture Mechanization,Purchase of agricultural machines \n,Suggested to register in SMAM ( Sub Mission on...,KERALA,TRIVANDRUM,NEMOM,2021-09-29T10:57:09.12
95399,NaN,AGRICULTURE,Others,Others,Government Schemes,PM KISAN related query.,Recommended SOBHA K G\nFather Name: K SADASIV...,KERALA,TRIVANDRUM,CHIRAYINKEEZHU,2021-09-29T12:10:02.153

In [6]:
ss = data_m['CreatedOn']
parsedDate = [parser.parse(i) for i in ss]

In [7]:
data_m['CreatedOn'] = parsedDate

In [8]:
data_m

,Season,Sector,Category,Crop,QueryType,QueryText,KccAns,StateName,DistrictName,BlockName,CreatedOn
0,NaN,HORTICULTURE,Vegetables,Others,0,subsidy loan,contact nabard-0483 2734084,KERALA,ALAPPUZHA,KANJIKKUZHY,2013-04-02 17:08:34.000
1,NaN,HORTICULTURE,Condiments and Spices,Nutmeg,0,nut meg fertilizer application,apply potash-2 kg per tree per year,KERALA,ALAPPUZHA,AMBALAPPUZHA,2013-04-02 17:33:32.000
2,NaN,HORTICULTURE,Plantation Crops,Coconut,0,coconut button shedding,apply borax 250 gm per palm per year,KERALA,ALAPPUZHA,THYCATTUSSERY,2013-04-04 10:52:07.000
3,NaN,HORTICULTURE,Vegetables,Mushroom,0,mushroom cultivation-training,contact KVK -0479 2270495,KERALA,ALAPPUZHA,THYCATTUSSERY,2013-04-04 10:53:47.000
4,NaN,HORTICULTURE,Condiments and Spices,Nutmeg,0,nut meg drop,apply borax 250 gm per plant per year( in seve...,KERALA,ALAPPUZHA,ARYAD,2013-04-04 11:18:09.000
...,...,...,...,...,...,...,...,...,...,...,...
95395,NaN,AGRICULTURE,Others,Others,Government Schemes,Govt schemes for farmers.,--Recommended that various schemes are pm kisa...,KERALA,TRIVANDRUM,KAZHAKUTTAM,2021-09-24 18:08:54.710
95396,NaN,HORTICULTURE,Plantation Crops,Coconut,\tPlant Protection\t,Button shedding in coconut,Recommended to give 100g borax per palm per ye...,KERALA,TRIVANDRUM,KAZHAKUTTAM,2021-09-25 13:13:57.963
95397,NaN,HORTICULTURE,Fruits,Papaya,\tPlant Protection\t,Fungal disease in Papaya,Recommended to give copper oxy chloride 2g per...,KERALA,TRIVANDRUM,VARKALA,2021-09-27 10:03:47.577
95398,NaN,AGRICULTURE,Others,Others,Agriculture Mechanization,Purchase of agricultural machines \n,Suggested to register in SMAM ( Sub Mission on...,KERALA,TRIVANDRUM,NEMOM,2021-09-29 10:57:09.120
95399,NaN,AGRICULTURE,Others,Others,Government Schemes,PM KISAN related query.,Recommended SOBHA K G\nFather Name: K SADASIV...,KERALA,TRIVANDRUM,CHIRAYINKEEZHU,2021-09-29 12:10:02.153

In [9]:
data_m.describe()

<ipython-input-9-491d8512b99a>:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  data_m.describe()

,Season,Sector,Category,Crop,QueryType,QueryText,KccAns,StateName,DistrictName,BlockName,CreatedOn
count,64,95400,95400,95400,95400,95400,93249,95400,95400,95400,95400
unique,3,6,23,327,98,43555,57432,1,10,123,92761
top,KHARIF,HORTICULTURE,Others,Others,\tPlant Protection\t,pest attack,Animal husbandry contact \r\nPlease contact 18...,KERALA,ERNAKULAM,0,2013-01-14 08:03:00
freq,25,63741,23907,24535,37433,1477,1053,95400,16212,7420,39
first,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-01-01 08:45:00
last,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-11 21:51:26.277000

## PySpark

In [10]:
spark = SparkSession.builder.getOrCreate()

KeyboardInterrupt: